// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVP7bIWyneXtDEAK5sYK8sC4OGyd74ElM',
    appId: '1:46596260129:web:365512cc5b4125b1477e60',
    messagingSenderId: '46596260129',
    projectId: 'balacona-652ca',
    authDomain: 'balacona-652ca.firebaseapp.com',
    storageBucket: 'balacona-652ca.firebasestorage.app',
    measurementId: 'G-V67RGRTBYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIMgnGE8lk6xpP2SR5dj0EmgTBNYwTZk',
    appId: '1:46596260129:android:8fa671540f733df7477e60',
    messagingSenderId: '46596260129',
    projectId: 'balacona-652ca',
    storageBucket: 'balacona-652ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTW54WjIcF76hrWRwdR0D0wVMkJCU_-4',
    appId: '1:46596260129:ios:6c3b7dbc9f65c8f4477e60',
    messagingSenderId: '46596260129',
    projectId: 'balacona-652ca',
    storageBucket: 'balacona-652ca.firebasestorage.app',
    iosClientId: '46596260129-otqrbb3g4sgl7lq84o52nm4r0qpn2ikt.apps.googleusercontent.com',
    iosBundleId: 'com.example.testttt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTW54WjIcF76hrWRwdR0D0wVMkJCU_-4',
    appId: '1:46596260129:ios:6c3b7dbc9f65c8f4477e60',
    messagingSenderId: '46596260129',
    projectId: 'balacona-652ca',
    storageBucket: 'balacona-652ca.firebasestorage.app',
    iosClientId: '46596260129-otqrbb3g4sgl7lq84o52nm4r0qpn2ikt.apps.googleusercontent.com',
    iosBundleId: 'com.example.testttt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVP7bIWyneXtDEAK5sYK8sC4OGyd74ElM',
    appId: '1:46596260129:web:c7289db56e99e449477e60',
    messagingSenderId: '46596260129',
    projectId: 'balacona-652ca',
    authDomain: 'balacona-652ca.firebaseapp.com',
    storageBucket: 'balacona-652ca.firebasestorage.app',
    measurementId: 'G-WS30STP4ET',
  );
}
